# World Cup Prediction 2026


## Objetivo
Campeón del mundo
Equipos que llegan a semifinales
Probabilidad de ganar por selección

##Datos
🔹 Datos de equipos

Ranking FIFA
Elo rating (más preciso que FIFA)
Goles anotados y recibidos
Forma reciente (últimos 10-20 partidos)
Resultados en mundiales anteriores

🔹 Datos de jugadores

Valor de mercado
Goles/asistencias
Lesiones

🔹 Variables de contexto

País anfitrión (USA, México, Canadá)
Clima / sedes
Experiencia en torneos grandes

👉 Fuentes comunes:
FIFA
Transfermarkt
FiveThirtyEight (soccer predictions)
Kaggle datasets

##Metricas nuevas

Promedio de goles
Diferencia de goles
% de victorias

##Links
https://www.kaggle.com/datasets/harrachimustapha/fifa-world-cup-team-dataset

https://www.kaggle.com/datasets/die9origephit/fifa-world-cup-2022-complete-dataset

##Entrada de Datos

In [ ]:
!pip install kagglehub[pandas-datasets]

In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import requests
import random

In [ ]:
file_path = "Fifa_world_cup_matches.csv"

# Load the latest version
df_matches = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "die9origephit/fifa-world-cup-2022-complete-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df_matches.head())

Using Colab cache for faster access to the 'fifa-world-cup-2022-complete-dataset' dataset.
First 5 records:            team1         team2 possession team1 possession team2  \
0          QATAR       ECUADOR              42%              50%
1        ENGLAND          IRAN              72%              19%
2        SENEGAL   NETHERLANDS              44%              45%
3  UNITED STATES         WALES              51%              39%
4      ARGENTINA  SAUDI ARABIA              64%              24%

  possession in contest  number of goals team1  number of goals team2  \
0                    8%                      0                      2
1                    9%                      6                      2
2                   11%                      0                      2
3                   10%                      1                      1
4                   12%                      1                      2

          date     hour category  ...  penalties scored team1  \
0  20 NOV 2022  17 : 00  Group A  ...                       0
1  21 NOV 2022  14 : 00  Group B  ...                       0
2  21 NOV 2022  17 : 00  Group A  ...                       0
3  21 NOV 2022  20 : 00  Group B  ...                       0
4  22 NOV 2022  11 : 00  Group C  ...                       1

   penalties scored team2  goal preventions team1  goal preventions team2  \
0                       1                       6                       5
1                       1                       8                      13
2                       0                       9                      15
3                       1                       7                       7
4                       0                       4                      14

   own goals team1  own goals team2  forced turnovers team1  \
0                0                0                      52
1                0                0                      63
2                0                0                      63
3                0                0                      81
4                0                0                      65

   forced turnovers team2  defensive pressures applied team1  \
0                      72                                256
1                      72                                139
2                      73                                263
3                      72                                242
4                      80                                163

   defensive pressures applied team2
0                                279
1                                416
2                                251
3                                292
4                                361

[5 rows x 88 columns]

In [ ]:
df_matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 88 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   team1                                                  64 non-null     object
 1   team2                                                  64 non-null     object
 2   possession team1                                       64 non-null     object
 3   possession team2                                       64 non-null     object
 4   possession in contest                                  64 non-null     object
 5   number of goals team1                                  64 non-null     int64
 6   number of goals team2                                  64 non-null     int64
 7   date                                                   64 non-null     object
 8   hour                                                   64 non-null     object
 9   category                                               64 non-null     object
 10  total attempts team1                                   64 non-null     int64
 11  total attempts team2                                   64 non-null     int64
 12  conceded team1                                         64 non-null     int64
 13  conceded team2                                         64 non-null     int64
 14  goal inside the penalty area team1                     64 non-null     int64
 15  goal inside the penalty area team2                     64 non-null     int64
 16  goal outside the penalty area team1                    64 non-null     int64
 17  goal outside the penalty area team2                    64 non-null     int64
 18  assists team1                                          64 non-null     int64
 19  assists team2                                          64 non-null     int64
 20  on target attempts team1                               64 non-null     int64
 21  on target attempts team2                               64 non-null     int64
 22  off target attempts team1                              64 non-null     int64
 23  off target attempts team2                              64 non-null     int64
 24  attempts inside the penalty area team1                 64 non-null     int64
 25  attempts inside the penalty area  team2                64 non-null     int64
 26  attempts outside the penalty area  team1               64 non-null     int64
 27  attempts outside the penalty area  team2               64 non-null     int64
 28  left channel team1                                     64 non-null     int64
 29  left channel team2                                     64 non-null     int64
 30  left inside channel team1                              64 non-null     int64
 31  left inside channel team2                              64 non-null     int64
 32  central channel team1                                  64 non-null     int64
 33  central channel team2                                  64 non-null     int64
 34  right inside channel team1                             64 non-null     int64
 35  right inside channel team2                             64 non-null     int64
 36  right channel team1                                    64 non-null     int64
 37  right channel team2                                    64 non-null     int64
 38  total offers to receive team1                          64 non-null     int64
 39  total offers to receive team2                          64 non-null     int64
 40  inbehind offers to receive team1                       64 non-null     int64
 41  inbehind offers to receive team2                       64 non-null     int64
 42  inbetween offers to receive team1                      64 non-null     int64
 43  inbetween offers to receive team2                      64 non-null     int64
 44  infront offers to receive team1                        64 non-null     int64
 45  infront offers to receive team2                        64 non-null     int64
 46  receptions between midfield and defensive lines team1  64 non-null     int64
 47  receptions between midfield and defensive lines team2  64 non-null     int64
 48  attempted line breaks team1                            64 non-null     int64
 49  attempted line breaks team2                            64 non-null     int64
 50  completed line breaksteam1                             64 non-null     int64
 51  completed line breaks team2                            64 non-null     int64
 52  attempted defensive line breaks team1                  64 non-null     int64
 53  attempted defensive line breaks team2                  64 non-null     int64
 54  completed defensive line breaksteam1                   64 non-null     int64
 55  completed defensive line breaks team2                  64 non-null     int64
 56  yellow cards team1                                     64 non-null     int64
 57  yellow cards team2                                     64 non-null     int64
 58  red cards team1                                        64 non-null     int64
 59  red cards team2                                        64 non-null     int64
 60  fouls against team1                                    64 non-null     int64
 61  fouls against team2                                    64 non-null     int64
 62  offsides team1                                         64 non-null     int64
 63  offsides team2                                         64 non-null     int64
 64  passes team1                                           64 non-null     int64
 65  passes team2                                           64 non-null     int64
 66  passes completed team1                                 64 non-null     int64
 67  passes completed team2                                 64 non-null     int64
 68  crosses team1                                          64 non-null     int64
 69  crosses team2                                          64 non-null     int64
 70  crosses completed team1                                64 non-null     int64
 71  crosses completed team2                                64 non-null     int64
 72  switches of play completed team1                       64 non-null     int64
 73  switches of play completed team2                       64 non-null     int64
 74  corners team1                                          64 non-null     int64
 75  corners team2                                          64 non-null     int64
 76  free kicks team1                                       64 non-null     int64
 77  free kicks team2                                       64 non-null     int64
 78  penalties scored team1                                 64 non-null     int64
 79  penalties scored team2                                 64 non-null     int64
 80  goal preventions team1                                 64 non-null     int64
 81  goal preventions team2                                 64 non-null     int64
 82  own goals team1                                        64 non-null     int64
 83  own goals team2                                        64 non-null     int64
 84  forced turnovers team1                                 64 non-null     int64
 85  forced turnovers team2                                 64 non-null     int64
 86  defensive pressures applied team1                      64 non-null     int64
 87  defensive pressures applied team2                      64 non-null     int64
dtypes: int64(80), object(8)
memory usage: 44.1+ KB

In [ ]:
df_matches.describe()

,number of goals team1,number of goals team2,total attempts team1,total attempts team2,conceded team1,conceded team2,goal inside the penalty area team1,goal inside the penalty area team2,goal outside the penalty area team1,goal outside the penalty area team2,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
count,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,...,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000
mean,1.578125,1.109375,11.140625,11.281250,1.109375,1.578125,1.468750,0.984375,0.093750,0.109375,...,0.140625,0.125000,11.593750,11.359375,0.015625,0.015625,71.968750,70.125000,289.750000,293.265625
std,1.551289,1.055856,4.972519,5.807682,1.055856,1.551289,1.563155,0.999876,0.293785,0.314576,...,0.350382,0.377964,5.911299,4.990045,0.125000,0.125000,14.394629,13.531269,88.406888,80.916230
min,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,38.000000,44.000000,139.000000,141.000000
25%,0.000000,0.000000,8.000000,7.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,7.750000,8.000000,0.000000,0.000000,63.000000,60.250000,229.000000,233.750000
50%,1.000000,1.000000,10.000000,10.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,11.000000,10.000000,0.000000,0.000000,71.000000,72.000000,281.000000,292.500000
75%,2.000000,2.000000,14.000000,14.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,14.000000,14.000000,0.000000,0.000000,83.500000,79.000000,328.000000,327.500000
max,7.000000,4.000000,25.000000,32.000000,4.000000,7.000000,7.000000,4.000000,1.000000,1.000000,...,1.000000,2.000000,32.000000,26.000000,1.000000,1.000000,101.000000,104.000000,637.000000,585.000000

In [ ]:
file_path = "test.csv"

# Load the latest version
df_teams = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "harrachimustapha/fifa-world-cup-team-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df_teams.head())

/tmp/ipykernel_2178/1240856043.py:4: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_teams = kagglehub.load_dataset(

Using Colab cache for faster access to the 'fifa-world-cup-team-dataset' dataset.
First 5 records:    version       team      continent  is_host  goals_scored_last_4y  \
0     2026     France         Europe        0                    85
1     2026      Spain         Europe        0                   104
2     2026  Argentina  South America        0                    80
3     2026    England         Europe        0                    82
4     2026   Portugal         Europe        0                    98

   goals_received_last_4y  wins_last_4y  losses_last_4y  draws_last_4y  \
0                      32            25               6              7
1                      32            29               2              8
2                      14            30               4              3
3                      23            26               6              7
4                      31            26               5              7

   world_cup_titles_before  ...  world_cup_participations_before  \
0                        2  ...                               16
1                        1  ...                               16
2                        3  ...                               18
3                        1  ...                               16
4                        0  ...                                8

   groups_passed_before  round16_before  quarterfinals_before  \
0                    10               8                     9
1                    11               9                     6
2                    15              10                    10
3                    13               8                    10
4                     5               4                     3

   semifinals_before  finals_before  winner  finalist  semi_finalist  \
0                  7              4     NaN       NaN            NaN
1                  2              1     NaN       NaN            NaN
2                  6              6     NaN       NaN            NaN
3                  3              1     NaN       NaN            NaN
4                  2              0     NaN       NaN            NaN

   quarter_finalist
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN

[5 rows x 24 columns]

In [ ]:
df_teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   version                          48 non-null     int64
 1   team                             48 non-null     object
 2   continent                        48 non-null     object
 3   is_host                          48 non-null     int64
 4   goals_scored_last_4y             48 non-null     int64
 5   goals_received_last_4y           48 non-null     int64
 6   wins_last_4y                     48 non-null     int64
 7   losses_last_4y                   48 non-null     int64
 8   draws_last_4y                    48 non-null     int64
 9   world_cup_titles_before          48 non-null     int64
 10  squad_total_market_value_eur     48 non-null     int64
 11  fifa_rank_pre_tournament         48 non-null     int64
 12  fifa_points_pre_tournament       48 non-null     float64
 13  squad_avg_age                    48 non-null     float64
 14  world_cup_participations_before  48 non-null     int64
 15  groups_passed_before             48 non-null     int64
 16  round16_before                   48 non-null     int64
 17  quarterfinals_before             48 non-null     int64
 18  semifinals_before                48 non-null     int64
 19  finals_before                    48 non-null     int64
 20  winner                           0 non-null      float64
 21  finalist                         0 non-null      float64
 22  semi_finalist                    0 non-null      float64
 23  quarter_finalist                 0 non-null      float64
dtypes: float64(6), int64(16), object(2)
memory usage: 9.1+ KB

In [ ]:
df_teams.describe()

,version,is_host,goals_scored_last_4y,goals_received_last_4y,wins_last_4y,losses_last_4y,draws_last_4y,world_cup_titles_before,squad_total_market_value_eur,fifa_rank_pre_tournament,...,world_cup_participations_before,groups_passed_before,round16_before,quarterfinals_before,semifinals_before,finals_before,winner,finalist,semi_finalist,quarter_finalist
count,48.0,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,4.800000e+01,48.000000,...,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,0.0,0.0,0.0,0.0
mean,2026.0,0.062500,72.395833,37.604167,21.354167,8.604167,9.854167,0.375000,3.117183e+08,32.520833,...,7.041667,4.062500,3.020833,2.437500,1.479167,0.708333,NaN,NaN,NaN,NaN
std,0.0,0.244623,18.037478,12.316292,5.923231,4.150056,3.614331,1.064415,3.450467e+08,23.819346,...,5.946422,5.187572,3.479359,4.078518,2.835861,1.761990,NaN,NaN,NaN,NaN
min,2026.0,0.000000,29.000000,14.000000,9.000000,2.000000,3.000000,0.000000,5.300000e+06,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,2026.0,0.000000,63.000000,30.000000,17.500000,6.000000,7.000000,0.000000,3.762500e+07,13.750000,...,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
50%,2026.0,0.000000,72.000000,34.500000,21.500000,8.000000,9.000000,0.000000,1.905750e+08,27.500000,...,6.000000,2.000000,2.000000,0.500000,0.000000,0.000000,NaN,NaN,NaN,NaN
75%,2026.0,0.000000,82.250000,42.000000,26.000000,11.250000,12.000000,0.000000,4.372125e+08,47.000000,...,11.000000,7.250000,5.000000,3.000000,2.000000,0.000000,NaN,NaN,NaN,NaN
max,2026.0,1.000000,110.000000,70.000000,37.000000,20.000000,20.000000,5.000000,1.300000e+09,85.000000,...,22.000000,20.000000,12.000000,17.000000,13.000000,8.000000,NaN,NaN,NaN,NaN

In [ ]:
# Set the path to the file you'd like to load
file_path = "eloratings.csv"

# Load the latest version
df_elo = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "saifalnimri/international-football-elo-ratings",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df_elo.head())

/tmp/ipykernel_2178/2523402526.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_elo = kagglehub.load_dataset(

Using Colab cache for faster access to the 'international-football-elo-ratings' dataset.
First 5 records:          date      team  rating  change
0  1872-11-30   England  2003.0       3
1  1872-11-30  Scotland  1997.0      -3
2  1873-03-08   England  2014.0      11
3  1873-03-08  Scotland  1986.0     -11
4  1874-03-07   England  2006.0      -8

In [ ]:
df_elo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6678 entries, 0 to 6677
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    6678 non-null   object
 1   team    6678 non-null   object
 2   rating  6647 non-null   float64
 3   change  6678 non-null   int64
dtypes: float64(1), int64(1), object(2)
memory usage: 208.8+ KB

In [ ]:
df_elo.describe()

            rating       change
count  6647.000000  6678.000000
mean   1490.960734     0.000000
std     299.252797    15.319033
min       0.000000   -86.000000
25%    1275.000000    -9.000000
50%    1511.000000     0.000000
75%    1712.000000     9.000000
max    2171.000000    86.000000

###API FIFA

In [ ]:
headers = {"Authorization": "Bearer fd_baaa1ff4dab0803ff56630bc5b98d850c2dc4ba0fe7028b3"}

url = "https://footballdata.io/api/v1/fifa-rankings?"

params = {
    "type": "men",
    "page": 1,
    "limit": 50   # intenta traer más equipos por página
}

response = requests.get(url, headers=headers, params=params)
data = response.json()

print(data)
for team in data["data"]:
    print(team["country"]["name"], team["points"]["total"])

{'success': False, 'error': {'code': 'paid_plan_required', 'message': 'This endpoint requires a paid plan.', 'details': {'current_plan': 'free', 'allowed_plans': ['starter', 'pro'], 'upgrade_required': True}}}

##MODELO

###Modelo 1

In [ ]:

elo_latest = (
    df_elo.sort_values("date")
    .groupby("team")
    .last()
    .reset_index()
)

elo_latest = elo_latest[["team", "rating"]]
elo_latest.rename(columns={"rating": "elo"}, inplace=True)

In [ ]:
df = df_teams.merge(elo_latest, on="team", how="left")

In [ ]:
df = df_teams.merge(elo_latest, on="team", how="left")

# eliminar equipos sin elo
df = df.dropna(subset=["elo"])

In [ ]:
df.head()

,version,team,continent,is_host,goals_scored_last_4y,goals_received_last_4y,wins_last_4y,losses_last_4y,draws_last_4y,world_cup_titles_before,...,groups_passed_before,round16_before,quarterfinals_before,semifinals_before,finals_before,winner,finalist,semi_finalist,quarter_finalist,elo
0,2026,France,Europe,0,85,32,25,6,7,2,...,10,8,9,7,4,NaN,NaN,NaN,NaN,2067.0
1,2026,Spain,Europe,0,104,32,29,2,8,1,...,11,9,6,2,1,NaN,NaN,NaN,NaN,1939.0
2,2026,Argentina,South America,0,80,14,30,4,3,3,...,15,10,10,6,6,NaN,NaN,NaN,NaN,2109.0
3,2026,England,Europe,0,82,23,26,6,7,1,...,13,8,10,3,1,NaN,NaN,NaN,NaN,2019.0
4,2026,Portugal,Europe,0,98,31,26,5,7,0,...,5,4,3,2,0,NaN,NaN,NaN,NaN,2041.0

In [ ]:
df["attack_strength"] = df["goals_scored_last_4y"] / df["goals_scored_last_4y"].mean()
df["defense_strength"] = df["goals_received_last_4y"] / df["goals_received_last_4y"].mean()
epsilon = 1e-6

df["defense_strength"] = df["defense_strength"].replace(0, epsilon)

In [ ]:
df["attack_strength"] = df["attack_strength"].clip(0.2, 3)
df["defense_strength"] = df["defense_strength"].clip(0.2, 3)

In [ ]:
df.head()

,version,team,continent,is_host,goals_scored_last_4y,goals_received_last_4y,wins_last_4y,losses_last_4y,draws_last_4y,world_cup_titles_before,...,quarterfinals_before,semifinals_before,finals_before,winner,finalist,semi_finalist,quarter_finalist,elo,attack_strength,defense_strength
0,2026,France,Europe,0,85,32,25,6,7,2,...,9,7,4,NaN,NaN,NaN,NaN,2067.0,1.137432,0.875092
1,2026,Spain,Europe,0,104,32,29,2,8,1,...,6,2,1,NaN,NaN,NaN,NaN,1939.0,1.391682,0.875092
2,2026,Argentina,South America,0,80,14,30,4,3,3,...,10,6,6,NaN,NaN,NaN,NaN,2109.0,1.070524,0.382853
3,2026,England,Europe,0,82,23,26,6,7,1,...,10,3,1,NaN,NaN,NaN,NaN,2019.0,1.097288,0.628973
4,2026,Portugal,Europe,0,98,31,26,5,7,0,...,3,2,0,NaN,NaN,NaN,NaN,2041.0,1.311392,0.847746

In [ ]:
df["win_rate"] = df["wins_last_4y"] / (
    df["wins_last_4y"] + df["draws_last_4y"] + df["losses_last_4y"]
)

In [ ]:
df.head()

,version,team,continent,is_host,goals_scored_last_4y,goals_received_last_4y,wins_last_4y,losses_last_4y,draws_last_4y,world_cup_titles_before,...,semifinals_before,finals_before,winner,finalist,semi_finalist,quarter_finalist,elo,attack_strength,defense_strength,win_rate
0,2026,France,Europe,0,85,32,25,6,7,2,...,7,4,NaN,NaN,NaN,NaN,2067.0,1.137432,0.875092,0.657895
1,2026,Spain,Europe,0,104,32,29,2,8,1,...,2,1,NaN,NaN,NaN,NaN,1939.0,1.391682,0.875092,0.743590
2,2026,Argentina,South America,0,80,14,30,4,3,3,...,6,6,NaN,NaN,NaN,NaN,2109.0,1.070524,0.382853,0.810811
3,2026,England,Europe,0,82,23,26,6,7,1,...,3,1,NaN,NaN,NaN,NaN,2019.0,1.097288,0.628973,0.666667
4,2026,Portugal,Europe,0,98,31,26,5,7,0,...,2,0,NaN,NaN,NaN,NaN,2041.0,1.311392,0.847746,0.684211

In [ ]:
df["experience"] = df["world_cup_participations_before"] * 0.1
df.head()

,version,team,continent,is_host,goals_scored_last_4y,goals_received_last_4y,wins_last_4y,losses_last_4y,draws_last_4y,world_cup_titles_before,...,finals_before,winner,finalist,semi_finalist,quarter_finalist,elo,attack_strength,defense_strength,win_rate,experience
0,2026,France,Europe,0,85,32,25,6,7,2,...,4,NaN,NaN,NaN,NaN,2067.0,1.137432,0.875092,0.657895,1.6
1,2026,Spain,Europe,0,104,32,29,2,8,1,...,1,NaN,NaN,NaN,NaN,1939.0,1.391682,0.875092,0.743590,1.6
2,2026,Argentina,South America,0,80,14,30,4,3,3,...,6,NaN,NaN,NaN,NaN,2109.0,1.070524,0.382853,0.810811,1.8
3,2026,England,Europe,0,82,23,26,6,7,1,...,1,NaN,NaN,NaN,NaN,2019.0,1.097288,0.628973,0.666667,1.6
4,2026,Portugal,Europe,0,98,31,26,5,7,0,...,0,NaN,NaN,NaN,NaN,2041.0,1.311392,0.847746,0.684211,0.8

In [ ]:
df["rating_total"] = (
    0.5 * df["elo"] +
    0.2 * df["fifa_points_pre_tournament"] +
    0.15 * df["win_rate"] * 100 +
    0.1 * df["experience"] * 100 +
    0.05 * (df["squad_total_market_value_eur"] / 1e9)
)
df.head()

,version,team,continent,is_host,goals_scored_last_4y,goals_received_last_4y,wins_last_4y,losses_last_4y,draws_last_4y,world_cup_titles_before,...,winner,finalist,semi_finalist,quarter_finalist,elo,attack_strength,defense_strength,win_rate,experience,rating_total
0,2026,France,Europe,0,85,32,25,6,7,2,...,NaN,NaN,NaN,NaN,2067.0,1.137432,0.875092,0.657895,1.6,1434.896921
1,2026,Spain,Europe,0,104,32,29,2,8,1,...,NaN,NaN,NaN,NaN,1939.0,1.391682,0.875092,0.743590,1.6,1371.991346
2,2026,Argentina,South America,0,80,14,30,4,3,3,...,NaN,NaN,NaN,NaN,2109.0,1.070524,0.382853,0.810811,1.8,1459.652912
3,2026,England,Europe,0,82,23,26,6,7,1,...,NaN,NaN,NaN,NaN,2019.0,1.097288,0.628973,0.666667,1.6,1400.759000
4,2026,Portugal,Europe,0,98,31,26,5,7,0,...,NaN,NaN,NaN,NaN,2041.0,1.311392,0.847746,0.684211,0.8,1391.571208

In [ ]:
avg_goals = (
    df_matches["number of goals team1"].mean() +
    df_matches["number of goals team2"].mean()
) / 2

BASE_GOALS = avg_goals  # normalmente ~1.3–1.6
print("Average goals:",BASE_GOALS)

Average goals: 1.34375

In [ ]:
def get_team_data(team):
    team = team.strip().lower()

    result = df[df["team"] == team]

    if result.empty:
        raise ValueError(f"Equipo no encontrado: {team}")

    return result.iloc[0]

In [ ]:
def expected_goals(teamA, teamB):
    A = get_team_data(teamA)
    B = get_team_data(teamB)

    base = BASE_GOALS

    epsilon = 1e-6

    attack_A = max(A["attack_strength"], epsilon)
    defense_B = max(B["defense_strength"], epsilon)

    attack_B = max(B["attack_strength"], epsilon)
    defense_A = max(A["defense_strength"], epsilon)

    lambda_A = base * (attack_A / defense_B)
    lambda_B = base * (attack_B / defense_A)

    # ajuste Elo
    elo_factor = np.exp((A["elo"] - B["elo"]) / 400)

    lambda_A *= elo_factor
    lambda_B /= elo_factor

    # ✅ asegurar valores válidos
    lambda_A = max(lambda_A, 0.05)
    lambda_B = max(lambda_B, 0.05)

    # ✅ evitar infinitos o NaN
    lambda_A = np.nan_to_num(lambda_A, nan=0.5, posinf=3, neginf=0.5)
    lambda_B = np.nan_to_num(lambda_B, nan=0.5, posinf=3, neginf=0.5)

    return lambda_A, lambda_B

In [ ]:
print(df[["team", "elo", "attack_strength", "defense_strength"]].head())

        team     elo  attack_strength  defense_strength
0     france  2067.0         1.137432          0.875092
1      spain  1939.0         1.391682          0.875092
2  argentina  2109.0         1.070524          0.382853
3    england  2019.0         1.097288          0.628973
4   portugal  2041.0         1.311392          0.847746

In [ ]:
def simulate_match(teamA, teamB):
    lambda_A, lambda_B = expected_goals(teamA, teamB)

    goals_A = np.random.poisson(lambda_A)
    goals_B = np.random.poisson(lambda_B)

    return goals_A, goals_B

In [ ]:
def knockout_match(teamA, teamB):
    goals_A, goals_B = simulate_match(teamA, teamB)

    # usar modelo híbrido SIEMPRE
    winner = hybrid_winner(teamA, teamB, goals_A, goals_B)

    return winner

In [ ]:
def simulate_round(team_list):
    teams = team_list.copy()
    random.shuffle(teams)

    winners = []

    # si hay número impar, uno pasa automáticamente
    if len(teams) % 2 == 1:
        winners.append(teams.pop())

    for i in range(0, len(teams), 2):
        winners.append(knockout_match(teams[i], teams[i+1]))

    return winners

In [ ]:
teams_list = df["team"].tolist()

def simulate_tournament():
    current = teams_list.copy()

    while len(current) > 2:
        current = simulate_round(current)

    final1, final2 = current
    champion = knockout_match(final1, final2)

    return champion, final1, final2

In [ ]:
from collections import Counter

N = 10000

champions = []
finalists = []

for _ in range(N):
    champ, f1, f2 = simulate_tournament()
    champions.append(champ)
    finalists.extend([f1, f2])

KeyboardInterrupt:

In [ ]:
# 1. precalcular
ml_probs = {}
teams = df["team"].tolist()

for teamA in teams:
    for teamB in teams:
        if teamA != teamB:
            ml_probs[(teamA, teamB)] = ml_win_probability(teamA, teamB)

# 2. simulación

N = 1000

champions = []

for _ in range(N):
    champ, _, _ = simulate_tournament()
    champions.append(champ)

In [ ]:
champ_counter = Counter(champions)
final_counter = Counter(finalists)

print("🏆 Campeón:\n")
for team, count in champ_counter.most_common():
    print(f"{team}: {count/N:.2%}")

print("\n🥈 Finalistas:\n")
for team, count in final_counter.most_common():
    print(f"{team}: {count/(2*N):.2%}")

🏆 Campeón:

portugal: 10.40%
netherlands: 9.40%
france: 8.10%
colombia: 7.60%
spain: 5.70%
sweden: 5.30%
england: 4.40%
belgium: 4.30%
argentina: 4.30%
germany: 4.10%
mexico: 3.80%
brazil: 3.50%
turkey: 3.30%
japan: 3.10%
uruguay: 2.40%
austria: 2.10%
norway: 2.00%
croatia: 1.80%
switzerland: 1.70%
panama: 1.50%
canada: 1.40%
jordan: 1.40%
senegal: 1.10%
ecuador: 1.10%
qatar: 0.80%
scotland: 0.80%
iran: 0.80%
morocco: 0.70%
australia: 0.60%
egypt: 0.60%
haiti: 0.40%
paraguay: 0.30%
uzbekistan: 0.30%
iraq: 0.30%
ghana: 0.20%
algeria: 0.20%
tunisia: 0.20%

🥈 Finalistas:

france: 1.15%
portugal: 0.90%
netherlands: 0.90%
colombia: 0.75%
germany: 0.65%
argentina: 0.65%
brazil: 0.60%
mexico: 0.45%
spain: 0.40%
japan: 0.30%
england: 0.30%
belgium: 0.25%
sweden: 0.20%
turkey: 0.15%
austria: 0.15%
ecuador: 0.15%
australia: 0.10%
jordan: 0.10%
croatia: 0.10%
uzbekistan: 0.10%
egypt: 0.10%
panama: 0.10%
norway: 0.10%
morocco: 0.05%
haiti: 0.05%
canada: 0.05%
iraq: 0.05%
scotland: 0.05%
switzerland: 0.05%
tunisia: 0.05%

In [ ]:
champ_counter = Counter(champions)
final_counter = Counter(finalists)

print("🏆 Campeón:\n")
for team, count in champ_counter.most_common():
    print(f"{team}: {count/N:.2%}")

print("\n🥈 Finalistas:\n")
for team, count in final_counter.most_common():
    print(f"{team}: {count/(2*N):.2%}")

🏆 Campeón:

portugal: 19.49%
france: 19.31%
netherlands: 18.02%
spain: 6.53%
sweden: 5.20%
colombia: 4.94%
germany: 4.47%
england: 3.85%
mexico: 3.83%
brazil: 3.59%
argentina: 2.78%
belgium: 2.11%
japan: 1.21%
norway: 1.17%
turkey: 1.13%
austria: 0.57%
croatia: 0.51%
uruguay: 0.36%
canada: 0.26%
switzerland: 0.16%
jordan: 0.11%
panama: 0.07%
senegal: 0.07%
australia: 0.06%
ecuador: 0.05%
iran: 0.05%
paraguay: 0.04%
qatar: 0.03%
scotland: 0.02%
egypt: 0.01%

🥈 Finalistas:

france: 14.95%
portugal: 14.95%
netherlands: 14.01%
spain: 6.75%
colombia: 5.80%
sweden: 5.69%
germany: 5.18%
england: 4.61%
mexico: 4.52%
brazil: 4.15%
argentina: 3.88%
belgium: 3.00%
japan: 2.21%
norway: 2.08%
turkey: 1.65%
austria: 1.18%
croatia: 1.12%
uruguay: 0.88%
canada: 0.65%
jordan: 0.54%
switzerland: 0.52%
panama: 0.24%
senegal: 0.23%
ecuador: 0.21%
australia: 0.17%
qatar: 0.17%
iran: 0.15%
paraguay: 0.13%
scotland: 0.12%
morocco: 0.10%
egypt: 0.07%
uzbekistan: 0.06%
ghana: 0.01%
iraq: 0.01%
tunisia: 0.01%

###Modelo Machine Learning

In [ ]:
# quitar % y convertir a float
df_matches["possession team1"] = df_matches["possession team1"].str.replace('%', '').astype(float)
df_matches["possession team2"] = df_matches["possession team2"].str.replace('%', '').astype(float)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# features
X = df_matches[[
    "possession team1",
    "possession team2",
    "total attempts team1",
    "total attempts team2",
    "passes team1",
    "passes team2"
]]

# target
y = (df_matches["number of goals team1"] > df_matches["number of goals team2"]).astype(int)

model = RandomForestClassifier()
model.fit(X, y)

RandomForestClassifier()

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# features
X = df_matches[[
    "possession team1",
    "possession team2",
    "total attempts team1",
    "total attempts team2",
    "passes team1",
    "passes team2"
]].copy()

# diferencias (MUY importante)
X["possession_diff"] = X["possession team1"] - X["possession team2"]
X["attempts_diff"] = X["total attempts team1"] - X["total attempts team2"]

# target
y = (df_matches["number of goals team1"] > df_matches["number of goals team2"]).astype(int)

# limpiar datos
X = X.apply(pd.to_numeric, errors='coerce')
X = X.fillna(X.mean())

# entrenar
model = RandomForestClassifier(
n_estimators=50,  # antes 200
    max_depth=5,
    random_state=42
)
model.fit(X, y)

RandomForestClassifier(max_depth=5, n_estimators=50, random_state=42)

In [ ]:
def ml_win_probability(teamA, teamB):
    A = get_team_data(teamA)
    B = get_team_data(teamB)

    # features simuladas desde dataset equipos
    poss_A = A["win_rate"] * 100
    poss_B = B["win_rate"] * 100

    attempts_A = A["attack_strength"] * 10
    attempts_B = B["attack_strength"] * 10

    passes_A = A["win_rate"] * 500
    passes_B = B["win_rate"] * 500

    X_new = pd.DataFrame([{
        "possession team1": poss_A,
        "possession team2": poss_B,
        "total attempts team1": attempts_A,
        "total attempts team2": attempts_B,
        "passes team1": passes_A,
        "passes team2": passes_B,
        "possession_diff": poss_A - poss_B,
        "attempts_diff": attempts_A - attempts_B
    }])

    prob = model.predict_proba(X_new)[0][1]
    return prob

In [ ]:
def hybrid_winner(teamA, teamB, goals_A, goals_B):
    prob_ml = ml_win_probability(teamA, teamB)

    # probabilidad Poisson implícita
    prob_poisson = 1 if goals_A > goals_B else 0

    # mezcla
    alpha = 0.7  # peso Poisson
    combined_prob = alpha * prob_poisson + (1 - alpha) * prob_ml

    return teamA if random.random() < combined_prob else teamB

In [ ]:
def hybrid_winner(teamA, teamB, goals_A, goals_B):
    prob_ml = ml_probs.get((teamA, teamB), 0.5)

    diff = goals_A - goals_B
    prob_poisson = 1 / (1 + np.exp(-diff))

    alpha = 0.6
    combined = alpha * prob_poisson + (1 - alpha) * prob_ml

    return teamA if random.random() < combined else teamB

In [ ]:
def simulate_match(teamA, teamB):
    # Poisson (goles)
    lambda_A, lambda_B = expected_goals(teamA, teamB)

    goals_A = np.random.poisson(lambda_A)
    goals_B = np.random.poisson(lambda_B)

    # ML (probabilidad)
    prob_ml = ml_win_probability(teamA, teamB)

    # combinación híbrida
    if goals_A == goals_B:
        # desempate con ML
        if random.random() < prob_ml:
            goals_A += 1
        else:
            goals_B += 1

    return goals_A, goals_B

###Modelo Prueba

In [ ]:
import numpy as np
import random
from collections import Counter

# -------------------------------
# 1. Equipos y ratings
# -------------------------------
teams = {
    "Argentina": 2050,
    "Francia": 2000,
    "Brasil": 1980,
    "Inglaterra": 1950,
    "España": 1920,
    "Portugal": 1900,
    "Alemania": 1850,
    "México": 1750
}

team_list = list(teams.keys())

# -------------------------------
# 2. Convertir Elo → fuerza ofensiva
# -------------------------------
def expected_goals(teamA, teamB):
    eloA = teams[teamA]
    eloB = teams[teamB]

    base_goals = 1.5  # promedio mundial

    attack_strength_A = 10 ** ((eloA - 1500) / 400)
    defense_strength_B = 10 ** ((eloB - 1500) / 400)

    lambda_A = base_goals * (attack_strength_A / defense_strength_B)

    # lo mismo para B
    attack_strength_B = 10 ** ((eloB - 1500) / 400)
    defense_strength_A = 10 ** ((eloA - 1500) / 400)

    lambda_B = base_goals * (attack_strength_B / defense_strength_A)

    if teamA == "México":
      lambda_A *= 1.1

    return lambda_A, lambda_B

# -------------------------------
# 3. Simular marcador con Poisson
# -------------------------------
def simulate_match(teamA, teamB):
    lambda_A, lambda_B = expected_goals(teamA, teamB)

    goals_A = np.random.poisson(lambda_A)
    goals_B = np.random.poisson(lambda_B)

    return goals_A, goals_B

# -------------------------------
# 4. Partido knockout (con penales)
# -------------------------------
def knockout_match(teamA, teamB):
    goals_A, goals_B = simulate_match(teamA, teamB)

    if goals_A > goals_B:
        return teamA
    elif goals_B > goals_A:
        return teamB
    else:
        # empate → penales (50/50)
        return random.choice([teamA, teamB])

# -------------------------------
# 5. Simular ronda
# -------------------------------
def simulate_round(teams):
    random.shuffle(teams)
    winners = []

    for i in range(0, len(teams), 2):
        teamA = teams[i]
        teamB = teams[i+1]
        winner = knockout_match(teamA, teamB)
        winners.append(winner)

    return winners

# -------------------------------
# 6. Simular torneo completo
# -------------------------------
def simulate_tournament():
    current = team_list.copy()

    while len(current) > 2:
        current = simulate_round(current)

    # Final
    finalist1, finalist2 = current
    champion = knockout_match(finalist1, finalist2)

    return champion, finalist1, finalist2

# -------------------------------
# 7. Monte Carlo
# -------------------------------
N = 10000

champions = []
finalists = []

for _ in range(N):
    champ, f1, f2 = simulate_tournament()
    champions.append(champ)
    finalists.extend([f1, f2])

# -------------------------------
# 8. Resultados
# -------------------------------
champ_counter = Counter(champions)
final_counter = Counter(finalists)

print("🏆 Probabilidad de campeón:\n")
for team, count in champ_counter.most_common():
    print(f"{team}: {count/N:.2%}")

print("\n🥈 Probabilidad de ser finalista:\n")
for team, count in final_counter.most_common():
    print(f"{team}: {count/(2*N):.2%}")

🏆 Probabilidad de campeón:

Argentina: 54.48%
Francia: 21.46%
Brasil: 13.77%
Inglaterra: 6.08%
España: 2.59%
Portugal: 1.44%
Alemania: 0.18%

🥈 Probabilidad de ser finalista:

Argentina: 35.19%
Francia: 22.30%
Brasil: 17.89%
Inglaterra: 11.02%
España: 7.18%
Portugal: 4.96%
Alemania: 1.39%
México: 0.07%